### ISSUE TITLE
GTDB taxonomy for CAT

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#111]
This is just to remember where I found this.

A tool to convert the GTDB taxonomy to the NCBI taxdump format that CAT uses: https://github.com/nick-youngblut/gtdb_to_taxdump

**Comment by danilodileo** [comment]
Do we want this feature for the release?

**Comment by erikrikarddaniel** [comment]
No, I think we can wait with this.

**Comment by danilodileo** [comment]
Since we are not sure whether we want to keep CAT, I will close this issue. we can open it again in the future.
