### ISSUE TITLE
Fix file arguments in `nextflow_schema.json`

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#116]
Our file parameters are declared as `string`, but I _think_ they should also have a `"format": "file-path"`. They also lack mime types and icons. There are a icons for a few typical biological file types, I think, the rest can have `far fa-file-code`. In my phyloplace pipeline I've used declarations such as this:
```
                "hmmfile": {
                    "type": "string",
                    "format": "file-path",
                    "mimetype": "text/plain",
                    "description": "HMM file. If provided, will be used to align both the reference and query sequences.",
                    "fa_icon": "far fa-file-code"
                }
```
I'm not sure what the guidelines say...

**Comment by danilodileo** [comment]
I can check the guidelines about it

**Comment by danilodileo** [comment]
We solve it for now with the PR #117  I will close it for now
