### ISSUE TITLE
Call featureCount on BBMap output to quantify ORFs

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#12]
There's an `nf-core` module available.

**Comment by erikrikarddaniel** [comment]
Make sure to encode the type of ORF caller in output file names. This can be done with the `options.suffix` (allows one to place a string in the output file name) or, better I think, by having one entry in `modules.config` for each ORF caller/annotator and set the `publish_dir` to e.g. `prokka/featureCount`.

**Comment by emnilsson** [comment]
Added in PR #38
