### ISSUE TITLE
kofamscan gets gzipped file from prodigal that it can't handle

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#138]
### Description of the bug

I think it would be best if the module can handle that.

It seems the program can take file input of the form: `<(gunzip -c prodigal.megahit.faa.gz)`, i.e. on the fly unzipping.

**Comment by danilodileo** [comment]
Hi Daniel, 

I don't get what you mean with this issue. the module kofamscan deals with gzipped files from prodigal by unzipping them and then gzipping the results.

**Comment by erikrikarddaniel** [comment]
The program doesn't need to explicitly gunzip the file, you can instead call it with the gzipped file using this syntax: `<(gunzip -c prodigal.megahit.faa.gz)`. This saves space by not leaving a gunzipped file in the work directory. 

This kind of syntax doesn't work with all programs, but I think I tested it with this. (Programs that tolerate this syntax need to read the input sequentially, i.e. must not try to go back in the file.)
