### ISSUE TITLE
Eukulele/GTDB: We're one rank off

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#148]
### Description of the bug

Domain is correct, phylum is skipped, then comes class in the phylum column, down to strain in the species column.

This was inherited from the Eukulele files, so we'd better get in touch with Arianna.

**Comment by danilodileo** [comment]
we checked this issue and. it looks ok. I will close it for now but we can open it if we see something odd in the future!
