### ISSUE TITLE
EUKULELE/GTDB summary tables

### ISSUE THREAD

**Issue by BenPonBiobrain** [LNUc-EEMiS/metatdenovo#149]
### Description of the bug

The eukulele output of metatdenovo does not get copied into the `summary_tables` output directory.
After running the pipeline, I found separate .csv files for each rank in the eukulele output dir.

Since the two files did not find their way into the summary_table dir, I had to manually go into the eukulele SUB work directory and copy the two files `default_summary.tsv.gz` and `default_taxonomy_classification.tsv.gz`.
If this is not unique to my case, maybe something to fix.

**Comment by erikrikarddaniel** [comment]
Thanks for the report!

I've found another bug: Phylum is left out and all the ranks below are off one step.

**Comment by danilodileo** [comment]
Hi I am going through the different bugs. I will make available default_taxonomy_classification.tsv.gz but I will not make available the summary.tsv.gz as it is included in the overall_stats.tsv.gz file!

**Comment by danilodileo** [comment]
Solved with PR #151
