### ISSUE TITLE
Clean up Eukulele search module

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#150]
### Description of the bug

1. The module (`EUKULELE`) is not named well, nor is the file (`eukulele/main.nf`). The name should be e.g. `EUKULELE_SEARCH` and the file should be `eukulele/search.nf` (remove `meta.yml`).
2. Don't do so much copying of data: Let `gunzip -c` write the file in the proper place or stage the file better (there should be a way of staging in a subdirectory).

**Comment by danilodileo** [comment]
solved with PR #153
