### ISSUE TITLE
`merge_tables` and `collect_stats` fails if sample names are just digits

### ISSUE THREAD

**Issue by emnilsson** [LNUc-EEMiS/metatdenovo#151]
### Description of the bug

As the description says, `merge_tables` fails when the sample names are just digits, e.g. "101". `union()` complains about `! x and y are not compatible.
✖ Incompatible types for column sample: character vs double.`. `collect_stats` fails due to similar reasons. Could we either make it possible to have samples that are named with just digits, or throw an error at the sample-check?

**Comment by danilodileo** [comment]
Solved with PR #152
