### ISSUE TITLE
Add assembler QC report

### ISSUE THREAD

**Issue by tfalkarkea** [LNUc-EEMiS/metatdenovo#162]
### Description of feature

Assembly quality can vary based on a large number of parameters, such as data type and quality. Tools like TransRate (https://hibberdlab.com/transrate/) can quickly analyze fasta files and generate metrics. These can be included in the final MultiQC report.

Another, more advanced, QC step would be to align the input reads to the generated assembly. Trinity recommends about 80% of the reads show up in the assembly, but this is likely going to be lower for meta-transcriptomes. 

I foresee the TransRate existing as a module, and the Bowtie assembly alignment would be a subworkflow.

**Comment by tfalkarkea** [comment]
@erikrikarddaniel feel free to assign me here!

**Comment by tfalkarkea** [comment]
Oh and the [Trinity suggestion](https://github.com/trinityrnaseq/trinityrnaseq/wiki/RNA-Seq-Read-Representation-by-Trinity-Assembly)

**Comment by erikrikarddaniel** [comment]
The second part of your suggestion (mapping reads back) is already done by the pipeline (using BBMap, an alternative to Bowtie). Currently we're outputting this in a text file that summarises quantitatively the different steps of the pipeline. In other words, the percent mapping back per sample is already there. (We see ~70% I think.) If you can add the numbers to the MultiQC report, @tfalkarkea , that would be great. 

(Mapping back is of course also used to quantify ORFs later in the pipeline. We use featureCount to summarize reads mapping to contigs that fall within ORFs.)

**Comment by taylorreiter** [comment]
FYI if you go down the transrate path, I had difficulties installing so thought I'd share:
1. I was able to get the pgcbioinfo docker container to run: https://hub.docker.com/r/pgcbioinfo/transrate/tags. It's built from this docker file: https://github.com/pgcbioinfo/containers/blob/5ebf3fc205501216c6f301c577f9ca5fcd029c77/transrate/Dockerfile-1.0.3. A lot of the other docker containers did not work (you can pull and run them, but they're missing deps).
2. In order for transrate to work, you do need unique fasta headers, and your headers cannot contain a pipe (`|`).
3. the conda package failed for me: https://anaconda.org/bioconda/transrate. It failed with missing dependencies:
```
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
Dependencies are missing:
  - snap (1.0dev.96)
  - salmon (0.6.0)
To install only the reference-metrics dependencies:

To install all missing dependencies, run:
  transrate --install-deps all
```
I installed these deps both with conda, and with the transrate command, and neither removed the error. Others have suggested that they got it to work with conda following instructions like [these](https://github.com/blahah/transrate/compare/master...pmomadeira:transrate:v1.0.4.1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23) but I was not successful with that either.

**Comment by tfalkarkea** [comment]
Thanks for the heads up! I had already set up my own custom module and found success with just the transrate biocontainer. Had you tried that container? 

I'm also only using transrate for the simple statistics instead of trying to map reads back.

```
process TRANSRATE {
    tag "$meta.id"

    container "quay.io/biocontainers/transrate:1.0.3--h031d066_5"

    input:
    tuple val(meta), path(assembly)

    output:
    path("*assemblies.csv")      , emit: assembly_qc
    path "versions.yml"          , emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args   ?: ''
    prefix   = task.ext.prefix ?: "${meta.id}"
    // tolerate both gzipped and normal inputs
    def gzipped = assembly.toString().endsWith(".gz") ? true : false
    """
    if $gzipped; then
      gzip -d -c $assembly > assembly_unzipped.fa
    else
      mv $assembly assembly_unzipped.fa
    fi

    transrate \\
      --threads $task.cpus \\
      --assembly assembly_unzipped.fa \\
      --output ${prefix}_transrate \\
      $args

    mv ${prefix}_transrate/assemblies.csv ${prefix}_assemblies.csv
}
```

**Comment by erikrikarddaniel** [comment]
Done in #167
