### ISSUE TITLE
Get a name for MultiQC based on combination of assembler and ORF caller

### ISSUE THREAD

**Issue by danilodileo** [LNUc-EEMiS/metatdenovo#163]
### Description of feature

We need to avoid that MultiQC gets overwritten if there are several runs with different combinations of assembler and ORF caller

**Comment by erikrikarddaniel** [comment]
@tfalkarkea , I've been working on a number of file naming issues and I think the best approach is to do as much as possible in `conf/modules.config`. There's a `saveAs` attribute in the `publishDir` part that can be used to set the file name. Hopefully, I'll make a PR on my parts today.

**Comment by danilodileo** [comment]
I close this issue as we solved it
