### ISSUE TITLE
Eukulele works poorly with `-resume`

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#176]
### Description of the bug

I've noticed that the Eukulele processes never resumes, and I think the download might be the problem. In the `EGGNOG` subworkflow we test for the presence of the db directory as well as a file, and skip the download step if the file is present. I think we should do something similar with Eukulele. See #168 though.

**Comment by danilodileo** [comment]
I can handle this issue. it will be partially address #168 issue too

**Comment by danilodileo** [comment]
the PR #190  will fix this issue

**Comment by danilodileo** [comment]
We fixed this issue in the last PR #190
