### ISSUE TITLE
Mix of filenames specified in modules.config and module code

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#177]
### Description of the bug

I think we're pretty close to having output file names, at least in `results/summary_tables` being prefixed by assembler and orf caller, but where this is specified is mixed. While I think the best solution is to use the `modules.config` file, it's not always practical. I cleaned up kofamscan for instance and managed to place this in the config file, but Eukulele summary output is still in the module. It fits quite well there, since this is the `-o` argument to the software (the Eggnog mapper is similar).

One thing we should remember is that although filenames in modules seem hardcoded, a user can specify a `prefix` in a config file and through that decide the name of output files. 

We should go through this and decide together.

**Comment by danilodileo** [comment]
Closing the issue since we are close to the release
