### ISSUE TITLE
when using EUKulele user's database error name output

### ISSUE THREAD

**Issue by danilodileo** [LNUc-EEMiS/metatdenovo#183]
### Description of the bug

EUKuele output is named improperl - 'assembler.orf_caller.[].taxonomy_classification.tsv.gz'  - It needs to be changed with a proper name. megahit.prokka.**name_database**.taxonomy_classification.tsv.gz

**Comment by erikrikarddaniel** [comment]
Does this happen both when using a supported database (e.g. PhyloDB) and a user defined?

**Comment by danilodileo** [comment]
It happens only when using custom database

**Comment by danilodileo** [comment]
fixed in the last PR #193
