### ISSUE TITLE
Eukulele duplicates, and other Eukulele small bugs

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#201]
### Description of the bug

In a project I ran for colleagues I found duplicates in the summary table. It turned out this was due to duplicates in the `taxonomy_estimation/prokka-estimated-taxonomy.out.gz` file. The ones I've looked at have different scores, so it seems we're not taking that into account:

```
0       FJKOKEPI_01799  species Bacteria; Gammaproteobacteria; Pseudomonadales; Porticoccaceae; HTCC2207; HTCC2207      HTCC2207        357.8   0
0       FJKOKEPI_01799  order   Bacteria; Gammaproteobacteria; Pseudomonadales  Pseudomonadales 287.0   1
...
0       CJDPECOA_05216  species Bacteria; Alphaproteobacteria; Puniceispirillales; Puniceispirillaceae; UBA8309; UBA8309        UBA8309 594.3   0
0       CJDPECOA_05216  family  Bacteria; Alphaproteobacteria; Puniceispirillales; Puniceispirillaceae; UBA8309; UBA8309        UBA8309 418.3   0
```

This should make this rather easy to deal with.

(What's a bit interesting above is that the last two lines are identical except for the score and the _rank_! Must be a Eukulele bug.)

Secondly, I also found that the summary table has capitalized names, e.g. `Domain`. It would be good to have all lowercase (IMO).

Thirdly, when one doesn't supply a database name, the summary file gets `[]` in the filename. This also affects the overall summary file in the form of `[]` in the column header for the eukulele counts.

**Comment by danilodileo** [comment]
we merged PR #202 so we can close this issue
