### ISSUE TITLE
It seems there's  a problem with Eukulele when using transdecoder

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#211]
### Description of the bug

I'm getting the following error message in a project. Will look into how to reproduce.

```
No samples found in sample directory with specified nucleotide or peptide extension.
```

Possibly because the fasta output from transdecoder has a `.pep` suffix.

Update 20231122 15:32: I ran the standard test case with `--orf_caller transdecoder --eukulele_db mmetsp` and that worked fine. My next guess is that it has to do with the uppmax profile that uses node local storage for input files. Will try that soon.

**Comment by danilodileo** [comment]
I think this is solved with the last updates. I will close it.

**Comment by erikrikarddaniel** [comment]
I'm afraid the issue wasn't solved.

**Comment by danilodileo** [comment]
Issue fixed.
