### ISSUE TITLE
Unable to obtain DAG file.

### ISSUE THREAD

**Issue by petemeng** [LNUc-EEMiS/metatdenovo#265]
### Description of the bug

```
nextflow run metatdenovo-1.0.0/main.nf --input samplesheet.csv --outfir result2 -profile docker -with-dag dag.html --skip_eukulele true
```

```
-[nf-core/metatdenovo] Pipeline completed successfully-
Completed at: 20-Feb-2024 18:50:32
Duration    : 1h 20m 57s
CPU hours   : 5.3
Succeeded   : 49
```

The command was run successfully, but no DAG file was obtained.

```[tasklist]
### Tasks
```

**Comment by erikrikarddaniel** [comment]
The `-with-dag` parameter is a Nextflow parameter so should work for any pipeline. There is no code in this pipeline to deal with this.

I ran the metatdenovo test case with the parameter and it produced a diagram. Not very readable perhaps, but at least it worked.

Command: `nextflow run nf-core/metatdenovo -r 1.0.0 -profile docker,test -with-dag dag.html`

I note that you have misspelled `--outdir` in your example above. Moreover, you know that you don't need to clone or download the pipeline code? This is done automatically by Nextflow if you call it following my example above.

**Comment by petemeng** [comment]
The nextflow 23.10 version can generate dag files normally, but the nextflow 23.04 version can't generate.

**Comment by erikrikarddaniel** [comment]
OK, then I close this issue as it seems to be a Nextflow issue.
