### ISSUE TITLE
Save log from Megahit

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#27]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/metatdenovo pipeline documentation](https://nf-co.re/metatdenovo/usage)

## Description of the bug

The standard output and error from the Megahit process is not caught by a named file output from the process.

## Expected behaviour

A log file should be saved in `results/megahit`.

**Comment by danilodileo** [comment]
I fixed this issue. It will be present in the next PR
