### ISSUE TITLE
 unpigz is invoked regardless of assembly file extension!

### ISSUE THREAD

**Issue by m3hdad** [LNUc-EEMiS/metatdenovo#276]
### Description of the bug

Some checkpoints are missing to ensure proper handling of assembly file.
`unpigz` is invoked regardless of file extension which removes the file content if assembly is in `fasta` format.

### Command used and terminal output

_Not applicable_

### Relevant files

_Not applicable_

### System information

_Not applicable_

**Comment by erikrikarddaniel** [comment]
Fixed in #277
