### ISSUE TITLE
Handle allowed values for orf caller better

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#32]
## Description of the bug

There's a way to specify allowed values for a parameter in `nextflow_schema.json` (see e.g. the `dada_ref_taxonomy` in the Ampliseq file). We should do the same for the orf caller parameter.

**Comment by danilodileo** [comment]
we should have done this, I think.  We specified three different key values that the user can use for orf_caller

**Comment by erikrikarddaniel** [comment]
Right, just close it. Normally, you'd mention the commit in which a bug was fixed in the closing message, but that is probably difficult this time. (I'm not closing it, since I didn't contribute...)
