### ISSUE TITLE
Some files are not published in the correct results directories, some files are published even though not specified

### ISSUE THREAD

**Issue by emnilsson** [LNUc-EEMiS/metatdenovo#35]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/metatdenovo pipeline documentation](https://nf-co.re/metatdenovo/usage)

## Description of the bug

The contigs-file from `megahit` is not published in `results/megahit` nor is the log from the same process (but that is already reported in #27.
In `results/bbmap` a `ref` directory is copied, and I cannot find where this is specified.
In `results/prokka` a directory for the different samples are created with all the `prokka`-output, which is not what I want, but I cannot figure out why.
There might be more oddities, but these are the ones I've spotted.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run . -profile docker,test --orf_caller prokka
2. See output in `results`

## Expected behaviour

I thought that the files you specify in `conf/modules.config` with e.g. `pattern` is what gets copied into the `results`-directory.

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [ ] The `.nextflow.log` file

## System

- Hardware: mac?
- Executor: local
- OS:  macOS 
- Version 10.14.6

## Nextflow Installation

- Version: 21.10.6

## Container engine

- Engine: Docker
- version: v20.10.11

**Comment by danilodileo** [comment]
I fixed this issue. It will be present in the future PR
