### ISSUE TITLE
Versions are not reported for `khmer` or `pigz` from the `UNPIGZ_MEGAHIT_CONTIGS`-process

### ISSUE THREAD

**Issue by emnilsson** [LNUc-EEMiS/metatdenovo#36]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/metatdenovo pipeline documentation](https://nf-co.re/metatdenovo/usage)

## Description of the bug

Versions are not reported in `results/pipeline_info/software_versions.yml` for `diginorm/khmer` or for `pigz` that is used in the `UNPIGZ_MEGAHIT_CONTIGS`-process. 

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run . -profile docker,test_diginorm --orf_caller prokka
2. See: `results/pipeline_info/software_versions.yml`

## Expected behaviour

That all versions are reported, at least for the processes that are run by the tests.

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: mac?
- Executor: local
- OS: macOS
- Version 10.14.6

## Nextflow Installation

- Version: 21.10.6

## Container engine

- Engine: Docker
- version: v20.10.11

**Comment by danilodileo** [comment]
I should have fixed it in the last eggnog PR 🤞🏼

**Comment by erikrikarddaniel** [comment]
When I fixed the hmm classification, I noticed the module for versions was placed too early in the script. I fixed that, so I'm closing this, but let's keep an eye on this!
