### ISSUE TITLE
`UNPIGZ_MEGAHIT_CONTIGS` is run even when `prokka` is used instead of `prodigal`

### ISSUE THREAD

**Issue by emnilsson** [LNUc-EEMiS/metatdenovo#37]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/metatdenovo pipeline documentation](https://nf-co.re/metatdenovo/usage)

## Description of the bug

The process `UNPIGZ_MEGAHIT_CONTIGS` is used to decompress the contigs coming from `megahit` before `prodigal` is run (I think this is the only reason, at least), but it is also run when `prokka` is specified instead.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run . -profile docker,test --orf_caller prokka
2. See error: -

## Expected behaviour

That unzipping the contig-files wasn't done if it's not needed.

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: mac?
- Executor: local
- OS: macOS
- Version 10.14.6

## Nextflow Installation

- Version: 21.10.6

## Container engine

- Engine: Docker
- version: v20.10.11

**Comment by danilodileo** [comment]
I should have fixed it in the eggnog PR! take a look :)
