### ISSUE TITLE
Cosmetics before release

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#56]
[ ] The `SUB_EUKULELE:EUKULELE_DB` module outputs `($meta.id)` (single quotes?)
[ ] Prokka output files end with an extra `.gz.faa`, `.gz.gff` etc.
[ ] When unzipping protein files the process name is `UNPIGZ_CONTIGS`
[ ] Process name for eukulele download, change to `EUKULELE_DOWNLOAD_DB`

**Comment by danilodileo** [comment]
Closing the issue since we are close to the release
