### ISSUE TITLE
RNASpades called multiple times

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#78]
As it is now, RNASpades will be called once for every pair of read files. There are a number of ways we could deal with this, but I think the best would be if we used the interleaved files that Megahit gets and wrote a yaml file looking like this:

```
[
  {
    orientation: "fr",
        type: "paired-end",
        interlaced reads: [
          "/home/dl/dev/metatdenovo/work/91/febcd19737053caccd6012ee9be7c3/SAMPLE1_PE_T1.fastq.gz",
          "/home/dl/dev/metatdenovo/work/bc/49c788e297c9648b76ac98268b0ef6/SAMPLE2_PE_T1.fastq.gz"
        ]
      }
  }
]
```

(Not tested.) See https://cab.spbu.ru/files/release3.12.0/manual.html#yaml.

Perhaps used in nf-core/mag?

**Comment by danilodileo** [comment]
we fixed this but in PR #95
