### ISSUE TITLE
prodigal output not coherent with orf id

### ISSUE THREAD

**Issue by danilodileo** [LNUc-EEMiS/metatdenovo#86]
The orf 'id' of prodigal output is weird. Both gff and .fna/.faa output have different names. 

As reported in prodigal repository with an issue https://github.com/hyattpd/Prodigal/issues/99 , the orfs get an extra "_1" or similar. this is problematic as none of gff, .fna and featurecounts tables have the same name. it will be impossible then merge the final tables. 
I guess that it is an issue inside prodigal, so what we could probably do it is to write an external code (new module for sub workflow)  that fix the tables after featurecounts.

**Comment by erikrikarddaniel** [comment]
Right. I think this is the reading frame. Have you seen any genes with another number than 1?

**Comment by danilodileo** [comment]
yes, it depends of the orfs

**Comment by danilodileo** [comment]
what I did was cutting the first part of the id (for example, "1_1" in "_1") and then paste it to the chr column.

**Comment by erikrikarddaniel** [comment]
Is it really sometimes "1_1"? I've only seen "_1".

**Comment by danilodileo** [comment]
![Screenshot 2023-01-19 at 17 29 51](https://user-images.githubusercontent.com/78909156/213498537-9ae955ab-973a-469e-b965-f3531573fc19.png)

here an example of table output

**Comment by erikrikarddaniel** [comment]
OK. The "_n" part doesn't seem to be the reading frame, but a counter for multiple orfs on the same contig. To uniquely identify an orf you hence need to keep the full name, you can't delete anything. What do the corresponding fasta files contain in terms of identifiers?

**Comment by danilodileo** [comment]
![Screenshot 2023-01-19 at 17 39 23](https://user-images.githubusercontent.com/78909156/213502017-1b55ce2e-5858-4e3c-af87-8485844d9321.png)


these are the names in the fasta file (orfs). the figure is from eukulele output and the names in the orf column are the same as the file .faa

**Comment by erikrikarddaniel** [comment]
Check the names of orfs from `k141_2562` which has two in the first table.

**Comment by danilodileo** [comment]
Solved in PR #87
