### ISSUE TITLE
Cat-ting after `prokka` only happens for one file when `--assembly`?

### ISSUE THREAD

**Issue by emnilsson** [LNUc-EEMiS/metatdenovo#88]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/metatdenovo pipeline documentation](https://nf-co.re/metatdenovo/usage)

## Description of the bug

I’m rerunning the pipeline to test with `gtdb` in `eukulele`, but I think something is broken when it comes to `prokka`. I’m providing my own assembly (because it forced me to rerun instead of `-resume`) with `--assembly`, and the `prokka`-part of that subworkflow runs for 48 files, but all the subsets are named `user_assembly`. The following `*_CAT` processes all just `cat` one `user_genome`, resulting in a lot of data lost.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run lnuc-eemis/metatdenovo -r dev -profile uppmax -params-file nextflow.yml -resume -c use_custom.config`

- `nextflow.yml` contains: `--input samples.csv --sequence_filter PATH --skip_trimming false --orf_caller 'prokka' --eggnog true --eggnog_dbpath PATH --skip_eukulele false --eukulele_dbpath PATH`

3. See error: No error provided, but the output of the `prokka`-subworkflow does not contain all the genes produced by `prokka`.

## Expected behaviour

That the output of the `prokka`-subworkflow should contain all the genes produced by `prokka`.

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: HPCslurm
- OS: Linux
- Version dev/v2.5.1-g55fa65c

## Nextflow Installation

- Version: 22.10.1

## Container engine

- Engine: singularity/apptainer
- version: ...

**Comment by erikrikarddaniel** [comment]
Odd, @danilodileo fixed this issue for megahit just a few days ago.

**Comment by emnilsson** [comment]
I could be misstaken, but I don't think so. My resulting `results/prokka/prokka.fna.gz` contains 9587 sequences/contigs, while my supplied assembly contains 984,244..

**Comment by danilodileo** [comment]
I think you are right, Emelie. It seems that the cat module takes only one entry as the output from prokka has always the same name (user_assembly.gff in this case). We need to change this behaviour so all the prokka outputs have different name as user_assembly.1.gff, user_assembly.2.gff, ect...)

**Comment by danilodileo** [comment]
I found the "issue". I can fix it and make a PR later or tomorrow.
