### ISSUE TITLE
Add KOfam_scan

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#92]
There is a Biocontainer: kofamscan.

The program call is documented here: https://github.com/erikrikarddaniel/biomakefiles/blob/master/lib/make/makefile.kofamscan (binary: `exec_annotation`)

Database files: https://www.genome.jp/ftp/db/kofam/ko_list.gz https://www.genome.jp/ftp/db/kofam/profiles.tar.gz

**Comment by danilodileo** [comment]
We added the module with #114  PR
